[package]
name = "type-sitter-gen"
version = "0.4.1"
authors = ["Jakob Hain <jakobeha@fastmail.com>"]
description = "generate typed wrappers for tree-sitter grammars from node-types.json and queries"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Jakobeha/type-sitter/"
categories = ["parsing", "compilers"]
keywords = ["type-sitter", "tree-sitter"]
edition = "2021"

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.56"
quote = "1.0.26"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
syn = "2.0.15"
indexmap = { version = "2.2.6", features = ["serde"] }
join-lazy-fmt = "0.9.2"
tree-sitter = "0.22.2"
lazy_static = "1.4.0"
cc = "1.0.79"
libloading = "0.8.0"
walkdir = "2.3.3"
logos = "0.14.0"
slice-group-by = "0.3.1"

[dev-dependencies]
prettyplease = "0.2.4"
pretty_assertions = "1.3.0"
