[package]
name = "type-sitter-lib"
version = "0.1.0"
description = "library code for type-sitter generated / downstream code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Jakobeha/type-sitter/"
categories = ["parsing", "compilers"]
keywords = ["type-sitter", "tree-sitter"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"

[features]
tree-sitter-wrapper = []

[dev-dependencies]
tree-sitter-rust = { path = "../vendor/tree-sitter-rust" }