[package]
name = "type-sitter-lib"
version = "0.1.0"
description = "library code for type-sitter generated / downstream code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Jakobeha/type-sitter/"
categories = ["parsing", "compilers"]
keywords = ["type-sitter", "tree-sitter"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"
nonempty = "0.8.1"

[dev-dependencies]
type-sitter = { path = "../type-sitter" }
tree-sitter-json = "0.19.0"
tree-sitter-cpp = "0.20.0"
tree-sitter-rust = "0.20.3"
tree-sitter-typescript = "0.20.2"