[package]
name = "type-sitter-lib"
version = "0.1.1"
description = "library code for type-sitter generated / downstream code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Jakobeha/type-sitter/"
categories = ["parsing", "compilers"]
keywords = ["type-sitter", "tree-sitter"]
edition = "2021"

[features]
tree-sitter-wrapper = []

[dependencies]
tree-sitter = "0.20.10"
once_cell = "1.17.1"
streaming-iterator = "0.1.9"

[dev-dependencies]
tree-sitter-rust = { path = "../vendor/tree-sitter-rust", version = "0.20.3" }
tree-sitter-json = { path = "../vendor/tree-sitter-json", version = "0.20.0" }
